apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello2-afsi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello2-afsi
    app.kubernetes.io/part-of: s
  name: java-springboot-hello2-afsi
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: java-springboot-hello2-afsi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: java-springboot-hello2-afsi
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/burrzinga-hac-tenant/s/java-springboot-hello2-afsi@sha256:1730cf891557325d419c887df2db23bee3125d3f0119d36713123faf0ce41a45
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
