apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello2-afsi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello2-afsi
    app.kubernetes.io/part-of: s
  name: java-springboot-hello2-afsi
  namespace: burrzinga-hac-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: java-springboot-hello2-afsi
    weight: null
status: {}
